services:
  postgres:
    container_name: nuro-api-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nuro-api
      - POSTGRES_PASSWORD=41d141c4cd38dba49f0abaff
      - POSTGRES_DB=nuro-api
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: nuro-api-redis
    image: redis:latest
    command: [redis-server, --maxmemory-policy, noeviction]
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  minio:
    container_name: nuro-api-minio
    image: minio/minio:latest
    command: [minio, server, /data, --console-address, ':9001']
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=nuro-api
      - MINIO_SECRET_KEY=41d141c4cd38dba49f0abaff
    volumes:
      - minio_data:/data
    healthcheck:
      test: [CMD, mc, ready, local]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  default: {}
